language: python
python:
  #- "2.6"
  - "2.7"  
# command to install dependencies
install:
  - curl http://python-distribute.org/distribute_setup.py | python
  - python setup.py install  
# command to run tests
script: python -m unittest discover