---
- hosts: all
  gather_facts: False  
  sudo: yes         
  tasks:
    - name: Setup passwordless ssh from master to workers
      authorized_key: user=root key="$master_pub_key"
    
    - include: configure_mapr.yml
      
    - name: Waiting for task tracker started
      wait_for: port=50060  
      
    - name: install gmond.conf
      template: src=gmond.conf.j2 dest=/etc/ganglia/gmetad.conf owner=root group=root
    
    - name: Restart ganglia service
      service: name=ganglia-monitor state=restarted pattern=ganglia-monitor  # pattern needed since the init script doesn't support status option
      
    